<a href="https://colab.research.google.com/github/vutt-ai-models/transformers_tutorials/blob/main/notebooks/Simple_Transformer_Language_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 61.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 33.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 135.4 MB/s eta 0:00:00


In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("distilgpt2") 
model = AutoModelForCausalLM.from_pretrained("distilgpt2", output_hidden_states=True)

In [6]:
text = "The Shawshank"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=100, do_sample=False)
print(output)
# Print the output
print('\n',tokenizer.decode(output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[  464, 18193,  1477,   962, 34433,     8,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198]])

 The Shawshank Redemption)
































































































In [7]:
# Print the token ides (of the input and output)
output

tensor([[  464, 18193,  1477,   962, 34433,     8,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198]])

## From words to vectors and back

In [9]:
# Print the input token ids
text = "The Shawshank"
input = tokenizer(text, return_tensors="pt")
input

{'input_ids': tensor([[  464, 18193,  1477,   962]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [ ]:
tokenizer.convert_ids_to_tokens(input[0])

['The', 'ĠShaw', 'sh', 'ank']

## Breathe meaning into numbers (Embedding)

In [ ]:
# This is the embedding matrix of the model
model.transformer.wte # Dimensions are: (Number of tokens in vocabulary, dimension of model)

Embedding(50257, 768)

In [ ]:
# Get the embedding vector of token # 464 ('The')
model.transformer.wte(torch.tensor(464))

In [12]:
text = "The chicken didn't cross the road because it was"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=50, num_beams=5, num_return_sequences=5, do_sample=True)
print(output)
# Print the output
print('\n',tokenizer.decode(output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[ 464, 9015, 1422,  470, 3272,  262, 2975,  780,  340,  373, 1165, 1263,
           11,  475,  340,  373,  991, 1165, 1263,   13,  198,  198,  198,  198,
          198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
          198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
          198,  198],
        [ 464, 9015, 1422,  470, 3272,  262, 2975,  780,  340,  373, 1165, 1263,
          329,  683,   13,  198,  198,  198,  198,  198,  198,  198,  198,  198,
          198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
          198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
          198,  198],
        [ 464, 9015, 1422,  470, 3272,  262, 2975,  780,  340,  373, 1165, 3024,
           13,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
          198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
          198,  198,  198,  198,  198,  198,  198,  198,  198,  1